DROP TABLE PET_CARE_LOG;


CREATE TABLE PET_CARE_LOG (
    PRODUCT_ID             NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    LOG_DATETIME           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    LAST_UPDATE_DATETIME   DATE,  
    CREATED_BY_USER        VARCHAR2(30),
    LOG_TEXT               VARCHAR2(500),
    UPDATED_BY_USER        VARCHAR2(30)
);

DROP TRIGGER TRG_PET_CARE_LOG_INSERT;

CREATE OR REPLACE TRIGGER TRG_PET_CARE_LOG_INSERT
BEFORE INSERT ON PET_CARE_LOG
FOR EACH ROW
BEGIN
    :NEW.LAST_UPDATE_DATETIME := SYSDATE;
    IF :NEW.CREATED_BY_USER IS NULL THEN      
        :NEW.CREATED_BY_USER := USER;
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20001, 'Insert trigger error: ' || SQLERRM);
END;

SELECT TRIGGER_NAME, STATUS
FROM USER_TRIGGERS
WHERE TRIGGER_NAME = 'TRG_PET_CARE_LOG_INSERT';

CREATE OR REPLACE TRIGGER trg_pet_care_log_update
BEFORE UPDATE ON PET_CARE_LOG
FOR EACH ROW
BEGIN
    IF :OLD.CREATED_BY_USER != USER THEN
        RAISE_APPLICATION_ERROR(-20002, 'Cant do: only self created records can be updated');
    END IF;

    :NEW.LAST_UPDATE_DATETIME := SYSDATE;
EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20002, 'Trigger error: ' || SQLERRM);
END;

CREATE OR REPLACE TRIGGER trg_pet_care_log_delete
BEFORE DELETE ON PET_CARE_LOG
FOR EACH ROW
BEGIN
    IF USER != 'JOEMANAGER' THEN
        RAISE_APPLICATION_ERROR(-20003, 'ONLY JOEMANAGER can delete records');
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20003, 'Delete error: ' || SQLERRM);
END;

INSERT INTO PET_CARE_LOG (CREATED_BY_USER, LOG_TEXT, UPDATED_BY_USER)
VALUES ('JOEMANAGER', 'Morning feeding for all dogs completed.', 'JOEMANAGER');

INSERT INTO PET_CARE_LOG (CREATED_BY_USER, LOG_TEXT, UPDATED_BY_USER)
VALUES ('JOEMANAGER', 'Quarterly inspection of all kennels passed.', 'JOEMANAGER');

INSERT INTO PET_CARE_LOG (CREATED_BY_USER, LOG_TEXT, UPDATED_BY_USER)
VALUES ('JOEMANAGER', 'End of week report filed. All animals healthy.', 'JOEMANAGER');

INSERT INTO PET_CARE_LOG (CREATED_BY_USER, LOG_TEXT, UPDATED_BY_USER)
VALUES ('SARAHSTAFF', 'Cleaned all cat litter boxes on floor 2.', 'SARAHSTAFF');

INSERT INTO PET_CARE_LOG (CREATED_BY_USER, LOG_TEXT, UPDATED_BY_USER)
VALUES ('SARAHSTAFF', 'Walked Daisy and Buddy around the yard.', 'SARAHSTAFF');

INSERT INTO PET_CARE_LOG (CREATED_BY_USER, LOG_TEXT, UPDATED_BY_USER)
VALUES ('MIKEVET', 'Administered vaccines to 3 rabbits in hutch B.', 'MIKEVET');

INSERT INTO PET_CARE_LOG (CREATED_BY_USER, LOG_TEXT, UPDATED_BY_USER)
VALUES ('MIKEVET', 'Checked on Rocky the bulldog, eating fine now.', 'MIKEVET');

INSERT INTO PET_CARE_LOG (CREATED_BY_USER, LOG_TEXT, UPDATED_BY_USER)
VALUES ('TOMCARE', 'Fed all reptiles and replaced UV bulb in tank 4.', 'TOMCARE');

INSERT INTO PET_CARE_LOG (CREATED_BY_USER, LOG_TEXT, UPDATED_BY_USER)
VALUES ('TOMCARE', 'Groomed Fluffy and trimmed nails on 2 other cats.', 'TOMCARE');

INSERT INTO PET_CARE_LOG (CREATED_BY_USER, LOG_TEXT, UPDATED_BY_USER)
VALUES ('JOEMANAGER', 'Reviewed vet reports for all animals. No concerns flagged.', 'JOEMANAGER');

-- TRIGGER 1: INSERT
-- Pass
INSERT INTO PET_CARE_LOG (CREATED_BY_USER, LOG_TEXT, UPDATED_BY_USER)
VALUES ('TESTUSER', 'Test insert log entry.', 'TESTUSER');

SELECT PRODUCT_ID, CREATED_BY_USER, LAST_UPDATE_DATETIME
FROM PET_CARE_LOG
WHERE CREATED_BY_USER = 'TESTUSER';
ROLLBACK;

-- Fail
INSERT INTO PET_CARE_LOG (CREATED_BY_USER, LOG_TEXT, UPDATED_BY_USER)
VALUES ('THIS_USERNAME_IS_WAY_TOO_LONG_FOR_THE_COLUMN', 'Some text.', 'TESTUSER');

ROLLBACK;

-- TRIGGER 2: UPDATE
-- Pass
INSERT INTO PET_CARE_LOG (CREATED_BY_USER, LOG_TEXT, UPDATED_BY_USER)
VALUES (USER, 'Original text.', USER);
COMMIT;
UPDATE PET_CARE_LOG
SET LOG_TEXT = 'Updated by owner.'
WHERE CREATED_BY_USER = USER;
COMMIT;
-- Fail
UPDATE PET_CARE_LOG
SET LOG_TEXT = 'Tampered text.'
WHERE CREATED_BY_USER = 'SARAHSTAFF';

ROLLBACK;

-- TRIGGER 3: DELETE
-- OPass
DELETE FROM PET_CARE_LOG WHERE PRODUCT_ID = 1;

ROLLBACK;
-- Fail
DELETE FROM PET_CARE_LOG WHERE PRODUCT_ID = 1;

ROLLBACK;