
-- 1)
class Comment(Base):
    __tablename__ = "comments"

    id         = Column(Integer, primary_key=True)
    task_id    = Column(Integer, ForeignKey("tasks.id", ondelete="CASCADE"), nullable=False)
    user_id    = Column(Integer, ForeignKey("users.id"), nullable=False)
    content    = Column(Text, nullable=False)
    created_at = Column(DateTime, server_default=func.current_timestamp())

    task = relationship("Task", back_populates="comments")
    user = relationship("User", back_populates="comments")

    
    def __repr__(self):
        return f"<Comment(id={self.id}, comment_id={self.task_id}, user_id={self.user_id})>"

-- 2)
"""Initial schema

Revision ID: d1e3c2324f2c
Revises: a7642e6512fc
Create Date: 2026-05-14 14:44:20.951036
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1e3c2324f2c'
down_revision = 'a7642e6512fc'
branch_labels = None
depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    # ### end Alembic commands ###

--3)
Team: DevOps3
User: diana_ops

Created Tasks:
   - Setup CI/CD (open)
   - Monitor systems (open)
   - Cleanup disk (open)

Total tasks: 6

Closed Task: Setup CI/CD

Deleting task: Cleanup disk

Remaining Tasks:
   - Fix login bug (open)
   - Design new dashboard (in_progress)
   - Update dependencies (open)
   - Setup CI/CD (closed)
   - Monitor systems (open)

CRUD operations completed!
